import type { Question } from './types';
// q1–q4 adapt the situations already used in src/content/scenes.ts.
// Additional questions paraphrase the same teaching points, not new quotations.
export const QUESTIONS: Question[] = [
 {id:'q1',topic:'rights',text:'Đời sống khá đầy đủ nhưng mọi quyết định lớn do thế lực bên ngoài đưa ra. Cộng đồng còn thiếu gì?',options:['Độc lập, quyền tự quyết','Chỉ thiếu của cải','Không thiếu gì','Chỉ thiếu hàng rào'],answer:0,explanation:'No đủ chưa thay thế quyền tự quyết của một dân tộc.',source:'Tình huống q1 · Tuyên ngôn Độc lập 1945'},
 {id:'q2',topic:'rights',text:'Nước có chủ quyền nhưng dân không có quyền cơ bản và đời sống không được bảo đảm. Hai giá trị còn thiếu là gì?',options:['Chỉ độc lập','Tự do và hạnh phúc','Chỉ tự do','Không còn thiếu giá trị nào'],answer:1,explanation:'Chủ quyền phải gắn với quyền của người dân và đời sống thực tế.',source:'Tình huống q2 · Thư gửi UBND các cấp, 17/10/1945'},
 {id:'q3',topic:'people',text:'Quyền đã được ghi nhận nhưng dân thiếu việc làm, giáo dục và chăm sóc y tế. Điều cần bổ sung trực tiếp là gì?',options:['Thêm khẩu hiệu','Chỉ mở rộng lãnh thổ','Điều kiện sống để có hạnh phúc','Bỏ các quyền đã ghi nhận'],answer:2,explanation:'Quyền cần được hiện thực hóa bằng điều kiện sống của từng người.',source:'Tình huống q3 · Nội dung ba cuốn sách'},
 {id:'q4',topic:'people',text:'Được học hành, có đời sống tốt và phát triển bản thân thuộc mục tiêu nào?',options:['Chỉ quan hệ đối ngoại','Chỉ chủ quyền lãnh thổ','Chỉ tổ chức chính quyền','Hạnh phúc của con người'],answer:3,explanation:'Hạnh phúc hướng tới đời sống và sự phát triển của con người.',source:'Tình huống q4 · Nội dung ba cuốn sách'},
 {id:'p5',topic:'people',text:'Việc nào trực tiếp cải thiện đời sống của người dân?',options:['Bảo đảm cơm ăn và học hành','Chỉ đổi tên cơ quan','Chỉ tăng số khẩu hiệu','Ngăn người dân học chữ'],answer:0,explanation:'Cơm ăn và học hành là những điều kiện cụ thể của đời sống.',source:'Diễn giải chủ đề Hạnh phúc'},
 {id:'p6',topic:'people',text:'Vì sao việc học chữ giúp các quyền có ý nghĩa thực tế hơn?',options:['Vì học chữ thay thế mọi quyền','Vì người dân có thêm khả năng hiểu và thực hiện quyền','Vì chỉ người biết chữ mới có quyền','Vì học chữ làm quyền tự quyết không cần thiết'],answer:1,explanation:'Giáo dục hỗ trợ khả năng thực hiện quyền; quyền không chỉ dành cho người biết chữ.',source:'Diễn giải tình huống q3'},
 {id:'p7',topic:'people',text:'Một xã có trường học nhưng nhiều trẻ không thể đến lớp vì thiếu điều kiện sống. Ưu tiên nào phù hợp?',options:['Coi như mục tiêu đã hoàn thành','Chỉ treo thêm biển trường','Hỗ trợ điều kiện để trẻ thực sự được học','Bỏ nhu cầu học tập'],answer:2,explanation:'Có cơ sở trên danh nghĩa chưa đủ; người dân cần có khả năng tiếp cận thực tế.',source:'Diễn giải chủ đề Hạnh phúc'},
 {id:'p8',topic:'people',text:'Cách hiểu nào đầy đủ hơn về hạnh phúc trong chủ đề này?',options:['Chỉ là có nhiều tiền','Chỉ là cảm xúc nhất thời','Chỉ là quyền của quốc gia','Đời sống được bảo đảm và có cơ hội phát triển'],answer:3,explanation:'Hạnh phúc được liên hệ với điều kiện sống và sự phát triển của con người.',source:'Diễn giải tình huống q4'},
 {id:'r5',topic:'rights',text:'Dấu hiệu nào thể hiện người dân là người chủ?',options:['Có tiếng nói và quyền tham gia việc chung','Chỉ nhận mệnh lệnh','Không được bày tỏ ý kiến','Không được biết quyết định chung'],answer:0,explanation:'Làm chủ gắn với tiếng nói và sự tham gia của nhân dân.',source:'Nội dung cuốn Tự do'},
 {id:'r6',topic:'rights',text:'Quan hệ nào phù hợp giữa ba giá trị?',options:['Có độc lập là tự động đủ tất cả','Độc lập tạo nền tảng, tự do và hạnh phúc đem lại ý nghĩa cho nền tảng ấy','Ba giá trị hoàn toàn không liên quan','Hạnh phúc khiến tự do không cần thiết'],answer:1,explanation:'Ba giá trị liên hệ với nhau, không thay thế nhau.',source:'Meaning Map · Nội dung dự án'},
 {id:'r7',topic:'rights',text:'Quốc gia tự quyết nhưng dân không được tham gia việc chung. Điều gì cần được củng cố?',options:['Từ bỏ chủ quyền','Ngừng cải thiện đời sống','Quyền làm chủ và tự do của người dân','Chỉ tăng khẩu hiệu'],answer:2,explanation:'Độc lập của quốc gia cần đi cùng quyền làm chủ của nhân dân.',source:'Diễn giải tình huống q2'},
 {id:'r8',topic:'rights',text:'Cách hiểu nào sai về độc lập?',options:['Dân tộc có quyền tự quyết','Là nền tảng cần được bảo vệ','Cần gắn với đời sống và quyền của dân','Có độc lập thì không cần quan tâm tự do, hạnh phúc'],answer:3,explanation:'Độc lập không làm cho tự do và hạnh phúc trở thành điều thừa.',source:'Diễn giải tình huống q1–q2'},
];
export const questionById = (id:string) => QUESTIONS.find(q=>q.id===id)!;
